### ISSUE TITLE
Convert to React Hooks

### ISSUE THREAD

**Issue by cujarrett** [cujarrett/js-pollock#2]
## What

Convert to React Hooks away from React Classes

**Comment by myteax** [comment]
What exactly is the issue?

**Comment by cujarrett** [comment]
@myteax The project is using older React classes currently and is like to convert it to use React hooks.

**Comment by myteax** [comment]
I could help you out with that, you can assign it to me

**Comment by cujarrett** [comment]
That would be awesome @myteax, the lib threw me for a wrench to convert when I took a look. Your help is very much appreciated!

**Comment by myteax** [comment]
Will work on it and  give you a feedback tomorrow.

**Comment by myteax** [comment]
https://github.com/myteax/js-pollock. - pull request created
